var Q = require('q');
var request = require('request');

module.exports = createApiClientForRelease;

function createApiClientForRelease(baseUrl, buildId, releaseName) {
    //defaults:
    releaseName = releaseName || (new Date()).toJSON();

    return {
        createRelease: createRelease,
        requestRun: requestRun,
        markRunsDone: markRunsDone
    };

    //returns {
    //            build_id: buildId,
    //            release_name: releaseName,
    //            release_number: number generated by dpxdt (e.g. 1, 2, 3 for the first, second, third releases)
    //            url: url generated by dpxdt for the release page
    //        }
    function createRelease() {
        return makeCall('create_release',
            {
                build_id: buildId,
                release_name: releaseName
            });
    }

    function requestRun(releaseName, releaseNumber, testName, url, config) {
        return makeCall('request_run',
            {
                build_id: buildId,
                release_name: releaseName,
                release_number: releaseNumber,
                run_name: testName,
                config: JSON.stringify(config), //The receiving API doesn't know how to accept a multi-key value
                url: url
            }
        );
    }

    function markRunsDone(buildId, releaseName, releaseNumber) {
        return makeCall('runs_done',
            {
                build_id: buildId,
                release_name: releaseName,
                release_number: releaseNumber
            }
        );
    }

    function makeCall(functionName, form) {
        var deferred = Q.defer();

        request.post(baseUrl + functionName, {
            form: form
        }, function (error, response, body) {
            if (error) {
                throw 'Error calling ' + functionName + ': ' + error;
            } else {
                var body = JSON.parse(body);
                if (body.error) {
                    throw 'Error calling ' + functionName + ': ' + error;
                }

                deferred.resolve(body);
            }
        });

        return deferred.promise;
    }
}

